---

scenario:
  test_sequence:
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
driver:
  name: docker
role_name_check: 1
provisioner:
  name: ansible
  config_options:
    defaults:
      deprecation_warnings: true
      callback_whitelist: timer,profile_tasks
      fact_caching: jsonfile
      fact_caching_connection: ./cache
      forks: 100
    connection:
      pipelining: true
  playbooks:
    converge: ../_shared/converge.yml
    verify: ../_shared/verify.yml
verifier:
  name: ansible
