---

- name: Verify
  hosts: all
  tasks:
    - name: COMMAND | Check if sury packages are available (PHP 8.0 does not exist on Debian repositories)
      ansible.builtin.command: apt-cache policy php8.0-common
      changed_when: false
      register: rez

    - name: FAIL | If Sury's package not found
      ansible.builtin.fail:
        msg: 'Sury fail'
      when: rez.stdout | length == 0
